// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import "./reset.css";

import { DataProvider } from "./dataGym";

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  );
}
